<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FILT111" failures="0" tests="5" name="Frontend_Testcases.LoginValidations" time="0.516" errors="1" timestamp="2023-08-07T12:16:48 IST" skipped="4">
  <testcase classname="Frontend_Testcases.LoginValidations" name="beforeSuite" time="0.516">
    <error message="Cannot invoke &quot;org.monte.media.MovieWriter.addTrack(org.monte.media.Format)&quot; because &quot;this.w&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.monte.media.MovieWriter.addTrack(org.monte.media.Format)" because "this.w" is null
at org.monte.screenrecorder.ScreenRecorder.createMovieWriter(ScreenRecorder.java:382)
at org.monte.screenrecorder.ScreenRecorder.start(ScreenRecorder.java:489)
at Recorder.MyScreenRecorder.startRecording(MyScreenRecorder.java:147)
at TestBase.JohnsonBase.beforeSuite(JohnsonBase.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeSuite -->
  <system-out/>
  <testcase classname="Frontend_Testcases.LoginValidations" name="blankUsernameBlankPassword" time="0.000">
    <skipped/>
  </testcase> <!-- blankUsernameBlankPassword -->
  <system-out/>
  <testcase classname="Frontend_Testcases.LoginValidations" name="validUsernameInvalidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- validUsernameInvalidPassword -->
  <system-out/>
  <testcase classname="Frontend_Testcases.LoginValidations" name="invalidUsernameValidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- invalidUsernameValidPassword -->
  <system-out/>
  <testcase classname="Frontend_Testcases.LoginValidations" name="validUsernameValidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- validUsernameValidPassword -->
  <system-out/>
</testsuite> <!-- Frontend_Testcases.LoginValidations -->
